require: rubocop-rails

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - db/**/*

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - bin/**/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true
